### PR TITLE
Fix ON DELETE/UPDATE being lost from self-referencing foreign key

### PR DESCRIPTION
**Pull request by kaorimatz**
DDLs TableParser::get_fks returns doesn't include `ON DELETE` or `ON UPDATE`, so constraints rebuilt by this plugin loses them.

https://github.com/percona/percona-toolkit/blob/129e28fe4a8726e3ffb0705780aadac31357cb8a/bin/pt-online-schema-change#L3545

When pt-osc rebuilds constraints it actually doesn't use TableParser::get_fks and use [this regexp](https://github.com/percona/percona-toolkit/blob/129e28fe4a8726e3ffb0705780aadac31357cb8a/bin/pt-online-schema-change#L10877-L10884) instead to find constraints. This PR changes the plugin to use the same [method](https://github.com/percona/percona-toolkit/blob/129e28fe4a8726e3ffb0705780aadac31357cb8a/bin/pt-online-schema-change#L10860-L10979).

This PR is based off of #9. You can see the diff from #9 [here](https://github.com/kaorimatz/cookpad_departure_defaults/compare/defer-rebuilding-self-referencing-foreign-key-until-copying-rows-is-done...kaorimatz:fix-on-delete-update-being-lost-from-self-referencing-foreign-key?w=1).

### CODE REVIEW

**Comment by errm** [comment]
Is this upstreamable?

**Comment by kaorimatz** [comment]
It should be possible to fix the issue in the upstream, but the patch would be quite different from this as this is just a plugin and I am not really sure how long it takes to get it released.

**Review by errm — APPROVED** [review]
LGTM

**Comment by kaorimatz** [comment]
Thank you for the review!

**Pull request merged**
